#!/bin/zsh

# Maximum minutes to wait until SoftwareRepoURL set
max_waiting_minutes=5

# Convert minutes to seconds
max_waiting_seconds=$((max_waiting_minutes * 60))

# Path to installer
munki_installer=/private/tmp/munkitools-6.6.5.4711.pkg

# Line you expect to get back from SoftwareRepoURL setting
url_test="SoftwareRepoURL: 'https://YOURORG.COM/munki_repo'"

# Location of the managedsoftwareupdate command
managedsoftwareupdate=/usr/local/munki/managedsoftwareupdate

if [[ ! -f $munki_installer ]]; then
    /bin/echo "ERROR: $munki_installer missing!"
    exit 1
fi

/bin/echo "Installing $munki_installer..."
/usr/sbin/installer -pkg $munki_installer -target /

if [[ ! -f $managedsoftwareupdate ]]; then
    /bin/echo "ERROR: Even though Munki installed, $managedsoftwareupdate is missing!"
    exit 1
fi

# Initialize counter in seconds waited
counter=0

# Presumably, the MDM would send down a configuration profile to set the Munki settings
/bin/echo "Waiting for Munki settings..."
while ! /usr/local/munki/managedsoftwareupdate --show-config | /usr/bin/grep "$url_test"; do
    if [[ $counter -gt $max_waiting_seconds ]]; then
    	/bin/echo "ERROR: Waited more than $max_waiting_seconds for $url_test. Giving up..."
    	exit 1
    fi
    /bin/sleep 2
    counter=$((counter + 2))
    /bin/echo "$url_test not present yet. Waited $counter seconds so far..."
done

/bin/echo "$url_test now present!"

/bin/echo "Setting Munki bootstrap mode..."
/usr/local/munki/managedsoftwareupdate --set-bootstrap-mode

/bin/echo "Logging out..."
/usr/bin/osascript -e 'tell app "loginwindow" to  «event aevtrlgo»'
